### ISSUE TITLE
Decide version of paust-db requirements

### ISSUE THREAD

**Issue by dragon0170** [paust-team/paust-db#106]
paust-db v0.1 release 전에 requirement의 version을 정하는 것이 필요해 보입니다.
* RocksDB
  * 현재 최신 버전 - v5.17.2
  * Dockerfile내 버전 - v5.17.2
* Go
  * 현재 최신 버전 - v1.11.5
  * Dockerfile내 버전 - v1.10.8
* Tendermint
  * 현재 최신 버전 - v0.30.0
  * Dockerfile내 버전 - v0.27.4

**Comment by elon0823** [comment]
Tendermint 는 logging 문제가 해결된 0.29.0 이상의 버전을 사용해야 하므로 v0.30.0 으로 테스트를 한번 해볼 필요가 있을 것 같네요
