### ISSUE TITLE
Change rocksdb default directory of paust-db master application

### ISSUE THREAD

**Issue by dragon0170** [paust-team/paust-db#108]
현재 `paust-db master` 명령어를 통해 master application을 실행하면 rocksdb 데이터 저장을 위한 default directory는 `/tmp`입니다. 
`/tmp` 경로의 경우 시스템 재부팅시 데이터가 사라지게 되므로 default directory를 tendermint의 `~/.tendermint` 처럼 `~/.paust-db`로 변경하는 것이 좋아보입니다.

**Comment by kwjooo** [comment]
@dragon0170 @elon0823 
이거 ~/.paust-db로 수정되어 있던데 close해도 해도되지 않을까요?
