### ISSUE TITLE
README 보완 이슈 

### ISSUE THREAD

**Issue by elon0823** [paust-team/paust-db#111]
- Requirement 작성(go, rocksdb, tendermint 버전 명시)
- RocksDB dependency mac/ubuntu 나눠서 install 가이드 (installation title 에 MacOS 뺴기)
- Run 이후 Status 체크하는 가이드 제공 (tm-monitor)
- Query/Fetch 할 시, 대량 시계열 데이터의 특성에 맞게 sample 수정

**Comment by kwjooo** [comment]
Requirement 작성완료
RocksDB dependency 수정완료
Status 가이드 제공 완료

**Comment by kwjooo** [comment]
sample에 어떠한 데이터를 담는 것이 적절한 지는 논의가 필요해 보임.
AMO의 use case를 sample로 하는 것은 어떨까요?

**Comment by elon0823** [comment]
sample 은 twitter data를 사용하기로 논의되었습니다.
