### ISSUE TITLE
Survey openfst background material

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#129]
**Reference**
#124 

query optimizeing에 사용될 이론인 fst에 대한 이해를 높이기 위해 openfst library의 background material survey.

survey 후 [여기](https://www.notion.so/FST-93920d1d31fe4710b57b3b51d169451c) 에 정리

조사할 자료
http://www.openfst.org/twiki/bin/view/FST/FstBackground

**Comment by elon0823** [comment]
앞으로 survey/study에 대한 이슈는 problem 을 정의한 issue의 comment 로 작성하도록 하겠습니다.
