### ISSUE TITLE
Study Rust language

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#130]
2Q에 사용할 언어로 rust가 선택되었고 이를 위해 rust language에 대한 study가 필요하여 본 이슈 생성.

material로 rust에서 공식지원하는 [book](https://doc.rust-lang.org/book/) 을 선정 (* 한글버전 [book](https://rinthel.github.io/rust-lang-book-ko/ch00-00-introduction.html))

**Comment by kwjooo** [comment]
[여기](http://sarojaba.github.io/rust-doc-korean/doc/tutorial.html#crates-and-the-module-system)도 참고할만 하네요

**Comment by elon0823** [comment]
앞으로 survey/study에 대한 이슈는 problem 을 정의한 issue의 comment 로 작성하도록 하겠습니다.
