### ISSUE TITLE
Add client error handling of putting zero-value timestamp data

### ISSUE THREAD

**Issue by dragon0170** [paust-team/paust-db#132]
### 문제 상황
현재 client cli를 통해 stdin이나 file으로 data를 put할 경우 데이터의 timestamp가 명시되지 않아도 put이 정상적으로 동작하고 paust-db에 저장됩니다. 이 경우에는 timestamp에 uint64의 default value인 0으로 설정되어 data가 put이 됩니다. 이는 적절한 data put 과정이 아니므로 timestamp를 명시해야 put이 되도록 바꾸어야 합니다.
또한 client cli의 argument를 통해 하나의 데이터를 put할 때도 stdin, file로 put할 때처럼 timestamp를 명시할 수 있는 기능을 추가하려고 합니다.

### 변경 사항
* Client interface의 Put function 내에서 InputDataObj의 timestamp가 0인 경우 에러를 발생하도록 수정.
* client cli에서 argument를 통해 단일 데이터 put할 때에도 flag로 timestamp 명시 가능하도록 변경. timestamp flag를 따로 명시하지않은 경우 현재 시간으로 timestamp가 설정됨.
* client README에 cli의 데이터 입력조건 추가.(ex. stdin, file을 통해 put할 때 timestamp, ownerkey는 필수)

**Comment by elon0823** [comment]
다음 PR 에 해당 내용을 반영하면 좋을 것 같습니다. 

#### 각 param, field 에 대한 limit length 에 대한 table 을 readme 에 추가로 작성

- timestamp : nanosec 길이
- ownerkey(->ownerid로 변경) : 64byte
- data : unlimited
- qualifier : unlimited 

일단 data, qualifier 가 엄청 길면 tx 데이터가 커지기 때문에 분할해서 tx 를 날리는 구조가 아직 아니라 tx 사이즈 제한에 걸릴수있다 라는 주의도 써놓으면될것같네요

**Comment by dragon0170** [comment]
https://github.com/paust-team/paust-db/issues/132#issuecomment-472318992
해당 댓글 내용은 @kwjooo 가 server, client 모두 작업해서 PR 날린다고 합니다.
