### ISSUE TITLE
Implement paust-db in rust language

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#142]
**Reference**
#131 

# paust-db rust 구현 기능
- Command line interface
[clap library](https://github.com/clap-rs/clap)을 이용하여 cli 환경을 구성하고 cli를 통해 paust-db server를 실행
- abci
[rust-abci](https://github.com/tendermint/rust-abci) 를 참고하여 abci를 구현합니다
- rocksdb
[rocksdb rust wrapper](https://github.com/rust-rocksdb/rust-rocksdb)를 이용하여 rocksdb를 rust 환경에서 test한 후 rocksdb 기능을 구현

**Comment by elon0823** [comment]
go 로 가기로 했기때문에 해당이슈를 닫습니다
