### ISSUE TITLE
Survey blockchain which is suitable for paust-db

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#154]
**문제점**
현 paust-db의 abci의 구조는 tendermint의 block에 담기는 데이터를 전혀 사용하지 못하고 있다. 같은 데이터가 abci와 tendermint에 2번씩 저장하는 구조를 가지고 있다(#128)

이를 해결하기 위해 tendermint block을 수정하여 paust-db에 최적화되게 설계할 수 있는 방법이 있을 수 있다. 하지만 이번 이슈는 tendermint가 아닌 다른 blockchain을 조사하여 paust-db에 적합한 blockchain이 있는 지 혹은 paust-db에 적용하면 좋을 blockchain의 특성이 있는 지를 조사하려 한다.

paust-db의 특성중 decentralization과 time series에 적합한 consensus와 ledger structure 측면에서 조사하려한다.

**Comment by kwjooo** [comment]
https://github.com/ontio/documentation/blob/master/vbft-intro/vbft-intro.md
온톨로지 재단에서 만든 consensus 별 비교표입니다. POW, POS, PBFT, VBFT(ontology consensus), Paxox,Raft 별로 비교가 되어있네요. VBFT가 무엇인지 볼 필요는 있을 것 같습니다

**Comment by elon0823** [comment]
reference #
