### ISSUE TITLE
Make PAUST Virtual Storage prototype

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#19]
**Reference**
#18

**목적**
Client에서 timeseries data를 쏘고 Server가 이를 받아 Tendermint core상에 저장하는 것이 목표이다.

**내용**
abci를 따르는 Server와 간단한 cli를 가지는 Client로 구성된다.
Client에서 cli는 json형식의 timeseries data를 server로  전달한다.
Server는 Client에서 전달받은 json 형식의 time series data를 Tendermint block에 저장하는데, 이 때 
rowkey의 구조는 {timestamp, userid, userdata}로 구성되며 하나의 블록에 저장할 때 timestamp를 기준으로 sort한다.
Due date : 12/7

**Comment by elon0823** [comment]
1Q 마무리후 close 예정입니다.
