### ISSUE TITLE
Design data storage structure which is optimized for time series database

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#62]
paust-db가 database로 사용하는 Rocksdb는 data storage structure에 memtable, sstable를 사용하는 LSM Tree구조를 사용하는데, 이는 timeseries에 최적화되어 설계된 것이 아니므로 paust-db는 timeseries에 최적화된 structure를 구상할 필요가 있어 보임.

**Comment by elon0823** [comment]
influx db 는 현재 paust-db 구조와 맞지않아서 배제함
