### ISSUE TITLE
Packaging and deploy script

### ISSUE THREAD

**Issue by kwjooo** [paust-team/paust-db#93]
테스트 용도인지 배포 용도인지에 따라 각각 다른 시나리오가 존재한다. 하지만 docker image 파일은 같다.
docker image파일은 tendermint의 dependency와 paust-db의 dependency를 자동으로 설치하는 데에 목적이 있다.
테스트 용도일 때, cluster를 단일 docker-machine에 4개의 container로 구성하며 이는 이미지를 빌드한 후 make localnet-start명령어를 통해 실행한다.

배포 용도일 때, validator set을 생성하고 각기 다른 docker-machine에서 동작하게한다. 이 후 validator node를 통해 필요한 데이터를 얻어 non-validator로써 참여한다.

**Comment by elon0823** [comment]
#101 해결되었습니다.
